### ISSUE TITLE
Bug (?) for Python 3.10

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/pure_eval#4]
I don't know if this really counts as a bug, but the following code works with Python 3.6 - 3.9, but fails with Python 3.10.0a3, possibly due to some changes in the parser.

```python
import ast
import sys

import executing
import pure_eval

a = 1, 2, 3

try:
    a[3]
except IndexError:
    ex = executing.Source.executing(sys.exc_info()[2])
    evaluator = pure_eval.Evaluator.from_frame(ex.frame)
    index = evaluator[ex.node.slice.value]
    # Python 3.10:
    # TypeError: node should be an ast.expr, not 'int'
    # Need to use:
    # index = evaluator[ex.node.slice]
    print(index)
```

**Comment by aroberge** [comment]
Addendum: this is essentially what I do now in my code:
```python
    if isinstance(ex.node.slice, ast.Constant): # Python 3.10(.0a3)
        index = evaluator[ex.node.slice]
    elif isinstance(ex.node.slice.value, ast.Constant): # Python 3.6-3.9
        index = evaluator[ex.node.slice.value]
    else:
        # do not continue
```

**Comment by alexmojaki** [comment]
There have definitely been recent changes to the AST in this area such as https://bugs.python.org/issue34822

But that was in 3.9, I don't know what's happening in this case. Either way it's not a pure_eval issue, it's just a matter of accessing the correct node. ast.Constant was introduced recently so I expect that's why that code fails in 3.7, but if you check isinstance(..., ast.expr) instead that might work.
